sudo: required
cache:
  directories:
    - $HOME/.m2
language: java
services:
  - docker
jdk:
  - oraclejdk11
  - openjdk11 
os:
  - linux
before_script:
  - mvn -B -V clean
script:
  - mvn -B -V test
install:
  - mvn -B -V install -DskipTests=true

